version: 0.2

phases:
  install:
    commands:
      - echo Installing serverless
      - npm install -g serverless
  pre_build:
  install:
    commands:
      - echo Installing source npm dependencies
      - npm install
  build:
  install:
    commands:
      - echo Deployment started on `date`
      - echo Deploing with Serverless Framework
      - sls deploy -v -s $ENV_NAME
  post_build:
  install:
    commands:
      - echo Deployment completed on `date`