service: sls-ci-cd
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1
  memorySize : 128
  timeout: 3

functions:
  hello:
    handler: handler.logger
    events:
      - http:
          path: message
          method: get
